CREATE USER app WITH LOGIN ENCRYPTED PASSWORD 'qwerty';

GRANT SELECT, INSERT ON TABLE all_ids TO app;

GRANT SELECT, INSERT, UPDATE ON TABLE members TO app;

GRANT SELECT ON TABLE leaders TO app;

GRANT SELECT, INSERT ON TABLE projects TO app;

GRANT SELECT, INSERT, UPDATE ON TABLE actions TO app;

GRANT SELECT, INSERT ON TABLE votes TO app;

GRANT SELECT ON TABLE trolls TO app;

